Add controllers
IvSiln/java-shareit pull request #3
Opened 2023-06-09 20:00 UTC by IvSiln

2023-06-10 11:37 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/EmailException.java
> +public class EmailException extends RuntimeException {
Мы не создаём классы исключений под каждую сущность или поле

Создаётся один общий класс исключений.
Бросая его, ты в сообщении будешь писать, что именно произошло.

Называй классы исключений соответствии с HTTP статус кодами которые они будут порождать! Например `BadRequestException` это код 400.

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ItemDto createItem(ItemDto itemDto, Long ownerId);
Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `itemService.createItem()`

Получается масло-масляное! 

Лучше: `itemService.create()` `itemService.update()`

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemStorage.getAllItems()
Плохо выбирать из хранилища все, а затем фильтровать...
Хранилище должно тебе отдать сразу то что нужно, у него должен быть такой метод.

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        itemOwnerCheckValidator(owner, newItem, userId);
itemOwnerCheckValidator - эта штука странная, толи валидирует, толи владельца устанавливает...
Зачем передали сюда id, если он есть у владельца?

Метод удали, а дальше прочти комментарий про `Optional` и подумай как тут переписать...

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public Collection<ItemDto> searchItemsByDescription(String text) {
`Collection` -> `List`

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (oldItem.getOwner().getId() != userId) {
В этом методе тоже смешение валидации и обновления - не делаем так. 
Мухи отдельно котлеты отдельно.

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void userIdValidator(Long userId) {
Это тоже нельзя назвать валидатором.
Валидация это проверка значения на адекватность, а то что пользователя с неким id не существует это просто так может случится, но id от этого не стал неправильным...

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    Item getItem(Long id);
Давай разграничивать хранилища и сервисы с помощью глаголов.
В хранилищах - find
В сервисах - get

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    Item getItem(Long id);
При выборке одиночных объектов из хранилища, полезно использовать `Optional`

Это поможет писать удобный код в функциональном стиле в сервисах и с него удобно начать погружение в мир функциональщины.

`Optional<Item> findItemById()`

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return user != null ? userMapper.toUserDto(user) : null;
Возвращать `null` некорректно ни при каких обстоятельствах! 
В данном случае необходимо кинуть исключение что пользователь не найден по такому то идентификатору

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +        validateId(id);
Не валидируем в хранилище. 
Проверка параметров это обязанность контроллера.
Проверка на наличие пользователя это в сервисе.
Хранилище занимается только своей работой - отдает сущность. И в идеале `Optional<User>`

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +        validateId(user.getId());
Этому коду место в сервисе...

2023-06-10 11:37 UTC, FanaticFiz commented on src/main/resources/application.properties
>  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
Я буду топить за то чтобы ты сразу привыкал к написанию файла свойств для приложения в формате `yaml -> application.yml`
Мне трудно сейчас представить проект в котором до сих пор на него не пересели ))

Соответственно - попрошу тебя этому следовать.

2023-06-11 23:15 UTC, IvSiln commented
Денис, Привет! Постарался исправить, замечания и недочеты.

2023-06-12 11:47 UTC, FanaticFiz approved these changes

2023-06-12 11:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    Optional<ItemDto> getItem(Long id);
А вот сервису Optional не нужен.
Сервис сходит за сущностью и если ее нет бросит исключение `NotFound`, поэтому тут или мы что то возвращаем или падаем.

2023-06-12 11:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemStorage.findAllItems().stream().filter(i -> i.getDescription().toLowerCase().contains(text.toLowerCase()) && i.getAvailable()).map(itemMapper::toItemDto).collect(Collectors.toList(
Плохо в сервисе сначала запрашивать все, а потом фильтровать.
Нужен метод в хранилище который отдаст сразу то что нужно.

2023-06-12 11:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void setOwnerIfValid(User owner, Item newItem) {
Комбинируя код в цепочки, через точку, желательно каждую отдельную операцию ставить на новую строку, вот так:

```
    private void setOwnerIfValid(User owner, Item newItem) {
        Optional.ofNullable(owner)
                .map(user -> {
                    newItem.setOwner(user);
                    return newItem;
                })
                .orElseThrow(() -> new NotFoundException("User not found"));
    }
 ```

2023-06-12 11:47 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    List<Item> findAllItemsById(Long userId);
Название ввело меня в ступор... как это все но по одному `id`, подумал я.
А оказывается это все для пользователя - соответственно лучше назвать: `findUserItems()`

2023-06-18 19:31 UTC, merged