Add bookings
IvSiln/java-shareit pull request #4
Opened 2023-06-27 08:53 UTC by IvSiln

Наконец-то прошли тесты

2023-06-27 20:08 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-06-27 20:08 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/EmailExistException.java
> +public class EmailExistException extends RuntimeException {
Не называй так конкретно класс исключения.
В веб сервисе уместно именовать по типу выбрасываемого кода.
Т.е. это у тебя `ConflictException` - произошел конфликт, он может быть не только у email, поэтому просто конфликт. 
А в сообщение уже ты говоришь что именно пошло не так...

2023-06-27 20:08 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
Написано два одинаковых обработчика для одного статуса... 
Можно объединить их и обработать в одном методе несколько исключений - поищи как это делается.

2023-06-27 20:08 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/OwnerBookingException.java
> +public class OwnerBookingException extends RuntimeException {
Не создаем таких специфичных исключений. Посмотри, что это у тебя, какой код возвращается, такой общий класс исключения и используй, а в сообщении описывай ситуацию конкретную.

2023-06-27 20:08 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query(" select i from Item i " +
Оформляй запросы, набирая команды SQL в верхнем регистре: `SELECT`.

2023-07-03 22:42 UTC, IvSiln commented on src/main/java/ru/practicum/shareit/exception/OwnerBookingException.java
> +public class OwnerBookingException extends RuntimeException {
![image](https://github.com/IvSiln/java-shareit/assets/39631093/f658dcbd-84ff-4fb7-a2c4-185476129bb7)
загнал таки

2023-07-04 21:45 UTC, FanaticFiz approved these changes

2023-07-04 21:45 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final ObjectMapper mapper = JsonMapper.builder()
Это теперь не используется... удалить

2023-07-04 21:45 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (state == State.UNSUPPORTED_STATUS) {//так работает, но как то не изящно получается
Так и это условие лишнее и статус такой нам не нужен! 

Будет кидаться `BadRequest` даже без добавления аннотации `@Valid`, если засылать статус которого нет в перечислении.

2023-07-04 21:45 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/enums/State.java
> +    UNSUPPORTED_STATUS, @JsonEnumDefaultValue
Не нужно добавлять того чего нет UNSUPPORTED_STATUS, UNKNOWN

2023-07-04 21:45 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case UNKNOWN:
Вместо `UNKNOWN` -> ` default:`

Идея то правильная, нужно что-то сделать когда вдруг придет не подходящий статус.
Но только нужно это сделать через default

2023-07-04 21:45 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        List<Long> itemIds = items.stream().map(Item::getId).collect(Collectors.toList());
Лишняя строка получилась

```
        trowIfNotExist(userId);
        
        List<Long> itemIds = itemRepository.findByOwnerId(userId).stream()
                                           .map(Item::getId)
                                           .collect(Collectors.toList());
        if (itemIds.isEmpty()) {
            return Collections.emptyList();
        }

        List<Booking> bookings;
        Instant now = Instant.now();
        switch (state) {
```

Обрати внимание и на отступы в виде пустых строк.
Что тоже важно.

Первое действие trowIfNotExist отдельно отделили пустой строкой. Визуально выделили это действие.

Второй шаг - получили itemIds и сделали return по условию - отделили, снова чтобы визуально выделить точку выхода из метода.

2023-07-04 21:45 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ExceptionHandler({ValidationException.class, UnsupportedStatusException.class, MethodArgumentNotValidException.class, MissingRequestHeaderException.class})
Строка вылезла за допустимые 120 символов.

```
    @ExceptionHandler({
            ValidationException.class,
            UnsupportedStatusException.class,
            MethodArgumentNotValidException.class,
            MissingRequestHeaderException.class})
    @ResponseStatus(HttpStatus.BAD_REQUEST)
```

2023-07-09 17:08 UTC, merged